/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmogenetico.Telas;

import algoritmogenetico.Classes.AlgoritmoGenetico;
import algoritmogenetico.Classes.Constantes;
import algoritmogenetico.Classes.Populacao;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.DatasetRenderingOrder;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYItemRenderer;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Milene
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Populacao pop;
    private JFreeChart panePop;
    private JFreeChart paneMedia;

//    private XYSeries curvaGrafico = new XYSeries("Função");
    private XYSeriesCollection curvaGrafico;
    private XYSeriesCollection populacaoGrafico;
    private XYSeriesCollection mediaPopulacao;

    private XYItemRenderer renderer2 = new StandardXYItemRenderer();
    private XYItemRenderer rendererMedia = new StandardXYItemRenderer();

    private XYPlot plot;
    private XYPlot plot2;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

//        CriarGrafico grafico1 = new CriarGrafico(plot, curvaGrafico);
//        CriarGrafico grafico2 = new CriarGrafico(plot2, mediaPopulacao);
        btnIniciarAg.setEnabled(false);

        //Inicializa gráfico Indivíduos
//        XYItemRenderer renderer2 = new StandardXYItemRenderer();
        ValueAxis domainAxis = new NumberAxis("Gerações");
        ValueAxis rangeAxis = new NumberAxis("Individuos");

//        grafico1.nameLabels("Gerações", "Individuos");
//        int[] eixoXGrafico = new int[]{0, 600};
//        int[] eixoYGrafico = new int[]{0, 600};
//        grafico1.configTamanho(eixoXGrafico, eixoYGrafico);
        domainAxis.setRange(0, 600);
        rangeAxis.setRange(0, 600);

//        grafico2.nameLabels("Gerações", "Média Fitness");
//        grafico2.configTamanho(eixoXGrafico, eixoYGrafico);
//        XYItemRenderer rendererMedia = new StandardXYItemRenderer();
        ValueAxis domainAxisMedia = new NumberAxis("Gerações");
        ValueAxis rangeAxisMedia = new NumberAxis("Media Fitness");
//        domainAxisMedia.setRange(0, 600);
//        rangeAxisMedia.setRange(0, 600);

        curvaGrafico = new XYSeriesCollection();

//        grafico1.geraGrafico();
//        grafico2.geraGrafico();
        plot = new XYPlot(curvaGrafico, domainAxis, rangeAxis, renderer2);
        plot2 = new XYPlot(mediaPopulacao, domainAxisMedia, rangeAxisMedia, rendererMedia);

//        grafico1.vinculaPaneChart("Evolução", panePop);
        panePop = new JFreeChart("Evolução", JFreeChart.DEFAULT_TITLE_FONT, plot, true);
//        panePop = new JFreeChart("Evolução", JFreeChart.DEFAULT_TITLE_FONT, grafico1.getPlot(), true);

//        grafico2.vinculaPaneChart("Média da População", paneMedia);
        paneMedia = new JFreeChart("Média da População", JFreeChart.DEFAULT_TITLE_FONT, plot2, true);
//        paneMedia = new JFreeChart("Média da População", JFreeChart.DEFAULT_TITLE_FONT, grafico2.getPlot(), true);

//        grafico1.addChartPane(jfcPopulacao, eixoYGrafico);
        jfcPopulacao.add(new ChartPanel(panePop));
        jfcPopulacao.setPreferredSize(new java.awt.Dimension(380, 316));

//        grafico2.addChartPane(jfcMediaPopulacao, eixoYGrafico);
        jfcMediaPopulacao.add(new ChartPanel(paneMedia));
        jfcMediaPopulacao.setPreferredSize(new java.awt.Dimension(380, 316));

        XYSeries series2 = new XYSeries("função");
        curvaGrafico.addSeries(series2);

        for (int i = 0; i < Constantes.functionXSize; i++) {
            series2.add(i, Constantes.function1(i));
        }

//        plot.setDataset(curvaGrafico);
//        plot.setRenderer(renderer2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcPopulacao = new javax.swing.JPanel();
        jfcMediaPopulacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMelhoresInd = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPioresInd = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTaxaCrossover = new javax.swing.JFormattedTextField();
        txtTaxaMutacao = new javax.swing.JFormattedTextField();
        txtIteracoes = new javax.swing.JFormattedTextField();
        btnCriarPop = new javax.swing.JButton();
        btnIniciarAg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Execução do Algoritmo Genético");

        jfcPopulacao.setPreferredSize(new java.awt.Dimension(376, 316));
        jfcPopulacao.setLayout(new javax.swing.BoxLayout(jfcPopulacao, javax.swing.BoxLayout.LINE_AXIS));

        jfcMediaPopulacao.setPreferredSize(new java.awt.Dimension(376, 316));
        jfcMediaPopulacao.setLayout(new java.awt.BorderLayout());

        txtMelhoresInd.setColumns(20);
        txtMelhoresInd.setRows(5);
        jScrollPane1.setViewportView(txtMelhoresInd);

        txtPioresInd.setColumns(20);
        txtPioresInd.setRows(5);
        jScrollPane2.setViewportView(txtPioresInd);

        jLabel1.setText("Melhores Indivíduos:");

        jLabel2.setText("Piores Indivíduos:");

        jLabel3.setText("Taxa de CrossOver: ");

        jLabel4.setText("Taxa de Mutção: ");

        jLabel5.setText("Evoluções: ");

        try {
            txtTaxaCrossover.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTaxaCrossover.setText("0.80");
        txtTaxaCrossover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxaCrossoverActionPerformed(evt);
            }
        });

        try {
            txtTaxaMutacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTaxaMutacao.setText("0.05");

        try {
            txtIteracoes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIteracoes.setText("00100");

        btnCriarPop.setText("Criar População");
        btnCriarPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPopActionPerformed(evt);
            }
        });

        btnIniciarAg.setText("Executar AG");
        btnIniciarAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarAgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(2, 2, 2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTaxaMutacao, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(txtTaxaCrossover))
                            .addComponent(txtIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIniciarAg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jfcPopulacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jfcMediaPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTaxaCrossover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriarPop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIniciarAg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfcPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfcMediaPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTaxaCrossoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxaCrossoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxaCrossoverActionPerformed

    private void btnCriarPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPopActionPerformed
        // TODO add your handling code here:

        btnIniciarAg.setEnabled(true);

        pop = new Populacao();

        XYItemRenderer renderer1 = new XYBarRenderer();

        XYSeries series1 = new XYSeries("Individuo");

        for (int j = 0; j < Constantes.sizePopulacao; j++) {
            series1.add(pop.getPopulacao()[j].getInt(), pop.getPopulacao()[j].getFitness()); //Double.toString(pop.getPopulacao()[j].getFitness())

        }

        populacaoGrafico = new XYSeriesCollection();

        populacaoGrafico.addSeries(series1);

        plot.setDataset(1, populacaoGrafico);
        plot.setRenderer(1, renderer1);

        plot.setDatasetRenderingOrder(DatasetRenderingOrder.FORWARD);
        jfcPopulacao.repaint();
        jfcPopulacao.revalidate();


    }//GEN-LAST:event_btnCriarPopActionPerformed

    private void btnIniciarAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarAgActionPerformed
        // TODO add your handling code here:

        double taxaMutacao = Double.parseDouble(txtTaxaMutacao.getText());
        double taxaCrossover = Double.parseDouble(txtTaxaCrossover.getText());
        int iteracoes = Integer.parseInt(txtIteracoes.getText());

        
        
        AlgoritmoGenetico ag = new AlgoritmoGenetico(taxaCrossover, taxaMutacao);

        XYSeries series3 = new XYSeries("media");

        mediaPopulacao = new XYSeriesCollection();
        mediaPopulacao.addSeries(series3);

        for (int i = 0; i <= iteracoes; i++) {
            pop = ag.executaAG(pop);

            series3.add(i, pop.getMediaPopulacao());

            populacaoGrafico = new XYSeriesCollection();
            XYSeries series = new XYSeries("individuos");
            populacaoGrafico.addSeries(series);

            jfcMediaPopulacao.removeAll();
            jfcPopulacao.removeAll();

            for (int j = 0; j < Constantes.sizePopulacao; j++) {
                series.add(pop.getPopulacao()[j].getInt(), pop.getPopulacao()[j].getFitness());
            }

            panePop = new JFreeChart("Evolução", JFreeChart.DEFAULT_TITLE_FONT, plot, true);
            paneMedia = new JFreeChart("Média da População", JFreeChart.DEFAULT_TITLE_FONT, plot2, true);

            jfcMediaPopulacao.add(new ChartPanel(paneMedia));
            jfcPopulacao.add(new ChartPanel(panePop));

            plot.setDataset(1, populacaoGrafico);
            plot2.setDataset(mediaPopulacao);

            jfcPopulacao.repaint();
            jfcPopulacao.revalidate();

            jfcMediaPopulacao.repaint();
            jfcMediaPopulacao.revalidate();
 
        }
        
        pop.OrdenarPopulacao();
        
        String prioresInds = "";
        for (int i = 0; i < 10; i++) {
             prioresInds += pop.getPopulacao()[i].printIndividuo() + "\n";
        }

        String melhoresInds = "";
        for (int i = Constantes.sizePopulacao - 1; i > (Constantes.sizePopulacao - 1) -10; i--) {
             melhoresInds += pop.getPopulacao()[i].printIndividuo() + "\n";
        }

        txtMelhoresInd.setText(melhoresInds);
        txtPioresInd.setText(prioresInds);

    }//GEN-LAST:event_btnIniciarAgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarPop;
    private javax.swing.JButton btnIniciarAg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jfcMediaPopulacao;
    private javax.swing.JPanel jfcPopulacao;
    private javax.swing.JFormattedTextField txtIteracoes;
    private javax.swing.JTextArea txtMelhoresInd;
    private javax.swing.JTextArea txtPioresInd;
    private javax.swing.JFormattedTextField txtTaxaCrossover;
    private javax.swing.JFormattedTextField txtTaxaMutacao;
    // End of variables declaration//GEN-END:variables
}
